# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 710f2uytrewrtyuiouytrsertyu987658897689q23waw3w2qawq2qaw2qa2wq2q2aw2qa2wq2w97ae60aecfad0fb0b625f220ae

test:
  secret_key_base: 02f025033c6834d0900a649e85e1624f6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
